export const Users = [
  { name: "Alice" },
  { name: "Bob" },
  { name: "Charlie" },
  { name: "David" },
  { name: "Eve" },
  { name: "Frank" },
  { name: "Grace" },
  { name: "Hank" },
  { name: "Ivy" },
  { name: "Jack" },
  { name: "Katie" },
  { name: "Leo" },
  { name: "Mike" },
  { name: "Nina" },
  { name: "Oliver" },
  { name: "Peter" },
  { name: "Quinn" },
  { name: "Rita" },
  { name: "Steve" },
  { name: "Tina" },
  { name: "Ursula" },
  { name: "Vera" },
  { name: "Walter" },
  { name: "Xander" },
  { name: "Yvonne" },
  { name: "Zoe" },
];
